import type { Metadata } from "next";
import AntdRegistry from "@/lib/nextjs-registry/AntdRegistry";
import "./index.css";
import { Noto_Sans_JP } from "next/font/google";
import { BaseLayout } from "@/components/Layouts/BaseLayout";
import { QueryProvider } from "@/lib/query/QueryProvider";

const notoSansJp = Noto_Sans_JP({
	subsets: ["latin"],
	weight: ["400", "700"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={notoSansJp.className}>
				<QueryProvider>
					<AntdRegistry>
						<BaseLayout>{children}</BaseLayout>
					</AntdRegistry>
				</QueryProvider>
			</body>
		</html>
	);
}
