"use client";

import {
	createCache,
	extractStyle,
	StyleProvider,
	type StyleProviderProps,
} from "@ant-design/cssinjs";
import { useServerInsertedHTML } from "next/navigation";
import { type FC, useRef, useState } from "react";

type AntdRegistryProps = Omit<StyleProviderProps, "cache">;

const AntdRegistry: FC<AntdRegistryProps> = (props) => {
	const [cache] = useState(() => createCache());
	const inserted = useRef(false);

	useServerInsertedHTML(() => {
		const styleText = extractStyle(cache, { plain: true });

		if (inserted.current) {
			return null;
		}
		inserted.current = true;

		return (
			// biome-ignore lint: SSRで安定したIDが必要
			<style
				id="antd-cssinjs"
				// to make sure this style is inserted before Ant Design's style generated by client
				data-rc-order="prepend"
				data-rc-priority="-1000"
				// biome-ignore lint/security/noDangerouslySetInnerHtml: Ant Designのスタイルを注入するために必要
				dangerouslySetInnerHTML={{ __html: styleText }}
			/>
		);
	});

	return <StyleProvider layer {...props} cache={cache} />;
};

export default AntdRegistry;
